export const query = `
select cr.RISK_ID ,c.CONTROL_ID,c.CONTROL_DESC, c.CONTROL_TEXT, c.CONTROL_TYPE_CODE, st.CONTROL_TYPE_DESC, c.CONTROL_CLASSIFICATION, 
f.FREQUENCY_CODE, f.FREQUENCY_DESC, c.FREQUENCY_MONTH
from CONTROL c
join CONTROL_FOR_RISK cr on c.CONTROL_ID=cr.CONTROL_ID and cr.DELETED_FLAG='N'
left join SOX_CONTROL_TYPE st on c.CONTROL_TYPE_CODE=st.CONTROL_TYPE_CODE
left join FREQUENCY f on c.FREQUENCY_CODE=f.FREQUENCY_CODE
where c.DELETED_FLAG='N'
`;
